{
 "title": "Weather",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Aktuálna teplota",
   "type": "gauge",
   "description": "Priemerná teplota z 3 senzorov.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rtl_433_temperature_celsius{location=\"temperature_sensors\"})",
     "legendFormat": "{{}}"
    }
   ]
  },
  {
   "title": "Aktuálna vlhkosť",
   "type": "gauge",
   "description": "Priemerná vlhkosť z 3 senzorov.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rtl_433_humidity{location=\"temperature_sensors\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Graf teploty zo senzorov",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "rtl_433_temperature_celsius{instance=\"$instance\", location=\"temperature_sensors\"}",
     "legendFormat": "{{model}} ({{id}})"
    }
   ]
  },
  {
   "title": "Posledné zachytené hodnoty teploty zo senzorov",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rtl_433_timestamp_seconds{instance=\"$instance\", location=\"temperature_sensors\"} * 1000",
     "legendFormat": "{{model}} ({{id}})"
    }
   ]
  },
  {
   "title": "Graf vlhkosti zo senzorov",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "rtl_433_humidity{location=\"temperature_sensors\"} * 100",
     "legendFormat": "{{model}} ({{id}})"
    }
   ]
  },
  {
   "title": "Posledné zachytené hodnoty vlhkosti zo senzorov",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rtl_433_timestamp_seconds{instance=\"$instance\", location=\"temperature_sensors\"} * 1000",
     "legendFormat": "{{model}} ({{id}})"
    }
   ]
  },
  {
   "title": "Teploty za posledných 12 hodín",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(avg(min_over_time(rtl_433_temperature_celsius{instance=\"$instance\", location=\"temperature_sensors\"}[12h:6m])))",
     "legendFormat": "Minimálna"
    },
    {
     "expr": "avg(avg_over_time(rtl_433_temperature_celsius{instance=\"$instance\", location=\"temperature_sensors\"}[12h:6m]))",
     "legendFormat": "Priemerná"
    },
    {
     "expr": "max(avg(max_over_time(rtl_433_temperature_celsius{instance=\"$instance\", location=\"temperature_sensors\"}[12h:6m])))",
     "legendFormat": "Maximálna"
    }
   ]
  },
  {
   "title": "Teploty za posledný deň",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(avg(min_over_time(rtl_433_temperature_celsius{instance=\"$instance\", location=\"temperature_sensors\"}[1d:6m])))",
     "legendFormat": "Minimálna"
    },
    {
     "expr": "avg(avg_over_time(rtl_433_temperature_celsius{instance=\"$instance\", location=\"temperature_sensors\"}[1d:6m]))",
     "legendFormat": "Priemerná"
    },
    {
     "expr": "max(avg(max_over_time(rtl_433_temperature_celsius{instance=\"$instance\", location=\"temperature_sensors\"}[1d:6m])))",
     "legendFormat": "Maximálna"
    }
   ]
  },
  {
   "title": "Teploty za posledných 7 dní",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(avg(min_over_time(rtl_433_temperature_celsius{instance=\"$instance\", location=\"temperature_sensors\"}[7d:6m])))",
     "legendFormat": "Minimálna"
    },
    {
     "expr": "avg(avg_over_time(rtl_433_temperature_celsius{instance=\"$instance\", location=\"temperature_sensors\"}[7d:6m]))",
     "legendFormat": "Priemerná"
    },
    {
     "expr": "max(avg(max_over_time(rtl_433_temperature_celsius{instance=\"$instance\", location=\"temperature_sensors\"}[7d:6m])))",
     "legendFormat": "Maximálna"
    }
   ]
  },
  {
   "title": "Teploty za posledných 30 dní",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(avg(min_over_time(rtl_433_temperature_celsius{instance=\"$instance\", location=\"temperature_sensors\"}[30d:6m])))",
     "legendFormat": "Minimálna"
    },
    {
     "expr": "avg(avg_over_time(rtl_433_temperature_celsius{instance=\"$instance\", location=\"temperature_sensors\"}[30d:6m]))",
     "legendFormat": "Priemerná"
    },
    {
     "expr": "max(avg(max_over_time(rtl_433_temperature_celsius{instance=\"$instance\", location=\"temperature_sensors\"}[30d:6m])))",
     "legendFormat": "Maximálna"
    }
   ]
  },
  {
   "title": "Stav batérie",
   "type": "bargauge",
   "description": "1 - dobrý\n0 - nízky",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rtl_433_battery{instance=\"$instance\", location=\"temperature_sensors\"}",
     "legendFormat": "{{model}} ({{id}})"
    }
   ]
  }
 ]
}