{
 "title": "Weather EN",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Current temperature",
   "type": "gauge",
   "description": "Current temperature from 3 sensors.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rtl_433_temperature_celsius{location=\"temperature_sensors\"})",
     "legendFormat": "{{}}"
    }
   ]
  },
  {
   "title": "Current humidity",
   "type": "gauge",
   "description": "Current humidity from 3 sensors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rtl_433_humidity{location=\"temperature_sensors\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature chart from sensors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "rtl_433_temperature_celsius{instance=\"$instance\", location=\"temperature_sensors\"}",
     "legendFormat": "{{model}} ({{id}})"
    }
   ]
  },
  {
   "title": "Last temperature measurements from sensors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rtl_433_timestamp_seconds{instance=\"$instance\", location=\"temperature_sensors\"} * 1000",
     "legendFormat": "{{model}} ({{id}})"
    }
   ]
  },
  {
   "title": "Humidity chart from sensors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "rtl_433_humidity{location=\"temperature_sensors\"} * 100",
     "legendFormat": "{{model}} ({{id}})"
    }
   ]
  },
  {
   "title": "Last humidity measurements from sensors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rtl_433_timestamp_seconds{instance=\"$instance\", location=\"temperature_sensors\"} * 1000",
     "legendFormat": "{{model}} ({{id}})"
    }
   ]
  },
  {
   "title": "Temperatures within last 12 hours",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(avg(min_over_time(rtl_433_temperature_celsius{instance=\"$instance\", location=\"temperature_sensors\"}[12h:6m])))",
     "legendFormat": "Lowest"
    },
    {
     "expr": "avg(avg_over_time(rtl_433_temperature_celsius{instance=\"$instance\", location=\"temperature_sensors\"}[12h:6m]))",
     "legendFormat": "Average"
    },
    {
     "expr": "max(avg(max_over_time(rtl_433_temperature_celsius{instance=\"$instance\", location=\"temperature_sensors\"}[12h:6m])))",
     "legendFormat": "Highest"
    }
   ]
  },
  {
   "title": "Temperatures within last day",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(avg(min_over_time(rtl_433_temperature_celsius{instance=\"$instance\", location=\"temperature_sensors\"}[1d:6m])))",
     "legendFormat": "Minimum"
    },
    {
     "expr": "avg(avg_over_time(rtl_433_temperature_celsius{instance=\"$instance\", location=\"temperature_sensors\"}[1d:6m]))",
     "legendFormat": "Average"
    },
    {
     "expr": "max(avg(max_over_time(rtl_433_temperature_celsius{instance=\"$instance\", location=\"temperature_sensors\"}[1d:6m])))",
     "legendFormat": "Maximum"
    }
   ]
  },
  {
   "title": "Temperatures within last 7 days",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(avg(min_over_time(rtl_433_temperature_celsius{instance=\"$instance\", location=\"temperature_sensors\"}[1d:6m])))",
     "legendFormat": "Lowest"
    },
    {
     "expr": "avg(avg_over_time(rtl_433_temperature_celsius{instance=\"$instance\", location=\"temperature_sensors\"}[1d:6m]))",
     "legendFormat": "Average"
    },
    {
     "expr": "max(avg(max_over_time(rtl_433_temperature_celsius{instance=\"$instance\", location=\"temperature_sensors\"}[1d:6m])))",
     "legendFormat": "Highest"
    }
   ]
  },
  {
   "title": "Temperatures within last 30 days",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(avg(min_over_time(rtl_433_temperature_celsius{instance=\"$instance\", location=\"temperature_sensors\"}[30d:6m])))",
     "legendFormat": "Lowest"
    },
    {
     "expr": "avg(avg_over_time(rtl_433_temperature_celsius{instance=\"$instance\", location=\"temperature_sensors\"}[30d:6m]))",
     "legendFormat": "Average"
    },
    {
     "expr": "max(avg(max_over_time(rtl_433_temperature_celsius{instance=\"$instance\", location=\"temperature_sensors\"}[30d:6m])))",
     "legendFormat": "Highest"
    }
   ]
  },
  {
   "title": "Battery status",
   "type": "bargauge",
   "description": "1 - high\n0 - low",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rtl_433_battery{instance=\"$instance\", location=\"temperature_sensors\"}",
     "legendFormat": "{{model}} ({{id}})"
    }
   ]
  }
 ]
}